version: '3.4'

networks:
    backend:
        driver: bridge

services:
  db:
    build: ./db 
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: studyproj
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    restart: always
    networks:
      - backend
  app:
    build: ./
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - backend
    environment:
      APP_PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@password:5432/studyproj