version: '3.4'

services:
  db:
    build: ./db 
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: studyproj
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    restart: always
  app:
    build: ./
    depends_on:
        - db
    ports:
      - 8080:8080
    